### ISSUE TITLE
Missing things:

### ISSUE THREAD

**Issue by i-am-the-slime** [rowtype-yoga/purescript-react-basic-dom-beta#1]
`autoFocus` on `input`

**Comment by i-am-the-slime** [comment]
`onKeyDown` and probably more like those on `input`

**Comment by i-am-the-slime** [comment]
`onChange` and probably more on `select`

**Comment by i-am-the-slime** [comment]
`width` and `height` on Image

**Comment by i-am-the-slime** [comment]
I think it's fine now, I guess.

**Comment by srghma** [comment]
also would be good to add docs to 

https://github.com/rowtype-yoga/purescript-yoga-react-dom/blob/c72b9263fda03bed69ff4ca905b1601b443d17bf/src/Yoga/React/DOM.purs#L42

what is the diff btw it and https://github.com/rowtype-yoga/purescript-yoga-react-dom/blob/c72b9263fda03bed69ff4ca905b1601b443d17bf/src/Yoga/React/DOM/Internal.purs#L14 (bc it's not used anywhere)
